#!/bin/bash
#cc markAsRead.c -o MARKDONE  2>/dev/null
#cc postit.c -o tnotes  2>/dev/null
#cc fgets.c -o gettxt  2>/dev/null
#cc addmore.c -o APPEND2  2>/dev/null
#cc addnote.c -o tnotescmd  2>/dev/null

# Comment out below if you want to debug #

cc ./src/markAsRead.c -o MARKDONE  2>/dev/null
cc ./src/postit.c -o tnotes 2>/dev/null
cc ./src/fgets.c -o gettxt  2>/dev/null
cc ./src/addmore.c -o APPEND2  2>/dev/null
cc ./src/addnote.c -o tnotescmd 2>/dev/null

mkdir -p /home/hexabit/.local/share/tpostit
cp -rf ../Terminal-post-it/*  /home/$USER/.local/share/tpostit/
echo 'alias tpostit="cd /home/$USER/.local/share/tpostit/;./tnotes"' >> /home/$USER/.bashrc
echo "alias tpostit 'cd /home/$USER/.local/share/tpostit/;./tnotes'" >> /home/$USER/.config/fish/config.fish

rm MARKDONE 
rm tnotes 
rm gettxt  
rm APPEND2  
rm tnotescmd  
echo "";echo"";
echo "DONE! Please restart your shell or source your shell's .rc and run \"tpostit\""
echo ""
#bash --init-file /home/$USER/.bashrc



